name: MinimalAppUninstaller
options:
  bundleIdPrefix: com.emredoganer
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    ENABLE_HARDENED_RUNTIME: YES

targets:
  MinimalAppUninstaller:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - "*.yml"
          - "*.md"
          - ".git/**"
          - "build/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.emredoganer.MinimalAppUninstaller
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: MinimalAppUninstaller.entitlements
        PRODUCT_NAME: MinimalAppUninstaller
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_APP_SANDBOX: NO
    entitlements:
      path: MinimalAppUninstaller.entitlements
